# Generated by Django 2.1.1 on 2018-10-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=10)),
                ('jam', models.TimeField()),
                ('nama', models.CharField(max_length=30)),
                ('tempat', models.CharField(max_length=30)),
                ('kategori', models.CharField(max_length=15)),
            ],
        ),
    ]
