# Generated by Django 2.1.1 on 2018-10-03 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
